---
- name: restart postgresql
  service:
    name: "{{ postgresql_daemon }}"
    state: "restarted"

- name: Force-restart PostgreSQL after new locales are generated.
  service:
    name: "{{ postgresql_daemon }}"
    state: restarted
